FROM node:22-alpine

WORKDIR /app

# Installation de pnpm
RUN npm install -g pnpm

# Copie du package.json uniquement
COPY package.json ./

# Installation des dépendances
RUN pnpm install

# Exposition du port
EXPOSE 3000

# Le code source sera monté en volume, pas besoin de COPY
CMD ["pnpm", "dev"]