FROM alpine:latest

RUN apk --no-cache add curl tzdata

ENV TZ=Europe/Paris
ENV APP_URL=http://app:3000

WORKDIR /app

COPY ./scripts/update-daily-country.sh /app/update-daily-country.sh

RUN chmod +x /app/update-daily-country.sh

RUN echo "0 0 * * * /app/update-daily-country.sh >> /var/log/cron.log 2>&1" > /etc/crontabs/root

RUN touch /var/log/cron.log

CMD crond -f -d 8 && tail -f /var/log/cron.log