version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CRON_API_SECRET=${CRON_API_SECRET}
      - PORT=3001
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs-app.rule=Host(`todays-flag.maillet.bzh`)"
      - "traefik.http.routers.nextjs-app.tls=true"
      - "traefik.http.routers.nextjs-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextjs-app.loadbalancer.server.port=3001"
      - "traefik.docker.network=traefik"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    environment:
      - CRON_API_SECRET=${CRON_API_SECRET}
      - APP_URL=http://app:3001
    depends_on:
      - app
    restart: always
volumes:
  mysql_data:

networks:
  traefik:
    external: true
