version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CRON_API_SECRET=${CRON_API_SECRET}

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    environment:
      - CRON_API_SECRET=${CRON_API_SECRET}
      - APP_URL=http://app:3000
    depends_on:
      - app
    restart: always
volumes:
  mysql_data:
