import Header from "@/components/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html className="h-full" lang="fr">
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground bg-[url('/assets/heroSection.png')] bg-cover bg-center bg-no-repeat
          flex flex-col h-full`}
        >
          <Header />
          <main className="flex-grow">{children}</main>
        </body>
      </html>
    </QueryProvider>
  );
}
